#ifndef VARIABLES_H
#define VARIABLES_H

enum Variables {
    ALLUSERSPROFILE,
    APPDATA,
    CommonProgramFiles,
    CommonProgramFilesx86,
    CommonProgramW6432,
    COMPUTERNAME,
    ComSpec,
    DriverData,
    HOMEDRIVE,
    HOMEPATH,
    LOCALAPPDATA,
    LOGONSERVER,
    NUMBER_OF_PROCESSORS,
    OneDrive,
    OneDriveConsumer,
    OS,
    Path,
    PATHEXT,
    POWERSHELL_DISTRIBUTION_CHANNEL,
    PROCESSOR_ARCHITECTURE,
    PROCESSOR_IDENTIFIER,
    PROCESSOR_LEVEL,
    PROCESSOR_REVISION,
    ProgramData,
    ProgramFiles,
    ProgramFilesx86,
    ProgramW6432,
    PROMPT,
    PSModulePath,
    PUBLIC,
    SESSIONNAME,
    SystemDrive,
    SystemRoot,
    TEMP,
    TMP,
    USERDOMAIN,
    USERDOMAIN_ROAMINGPROFILE,
    USERNAME,
    USERPROFILE,
    VBOX_MSI_INSTALL_PATH,
    windir,
    WSLENV,
    WT_PROFILE_ID,
    WT_SESSION,
    ZES_ENABLE_SYSMAN,
};

#endif // VARIABLES_H